apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: acc-suit-quest-get-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: acc-suit-quest-get-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /suitability/questions
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /suitability/questions
