include:
- ./func/*
kind: ArchiveUploadSpec
name: func-lCU9

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: suitability-questions-fn-e17d827e-693b-4b32-973e-af28f2d31973
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: suitability-questions-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-lCU9
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-10-02T21:16:09Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: suitability-questions-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: suitability-questions-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_suitability_questions
    packageref:
      name: suitability-questions-fn-e17d827e-693b-4b32-973e-af28f2d31973
      namespace: default
  requestsPerPod: 1
  resources: {}
